name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with: 
         submodules: 'recursive'
    - name: dependencies
      run: sudo apt-get install libeigen3-dev libfltk1.3-dev libopencv-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
